<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
$connection = $resource->getConnection();

$storecity = $block->getStoreCity();
$storestate = $block->getStoreState();
$storeCountry = $block->getStoreCountryName();
$storeZipcode = $block->getStorePincode();
$offDays = $block->getStoreOffDays();
$storeName = $block->getStoreName();

$sql = "SELECT * FROM store_pickup WHERE store_name = '$storeName'";
$data = $connection->fetchAll($sql);
$msg = "";
if($data[0]['is_home'] == 1){
    $msg = "<div class='tooltiptextstore'>Esta sucursal es asociada, y el costo de la instalación es de $75 MXN por neumático.<br>
    El costo de instalacion se cobra en suscursal.</div><br><br>
    <input type='hidden' value='otraSucursal' id='pagoOtraSucursal' name='pagoOtraSucursal'>";
}else{
    echo "<input type='hidden' value='sucursalPropia' id='pagoOtraSucursal' name='pagoOtraSucursal'>";
}
?>

<div id="mapView">
    <div id="storedetails">
        <p>
		<span>
			<strong><?php echo __('Tienda :'); ?></strong>
		</span>
            <span id="s_name" value="<?php echo $block->getStoreName(); ?>"><?php echo $block->getStoreName(); ?></span>
            <input type="hidden" name="store_name" value="<?php echo $block->getStoreName(); ?>">
        </p>
        <?php if (!empty($block->getStoreManagerName())) { ?>
            <p>
			<span>
				<strong><?php echo __('Responsable :'); ?></strong>
			</span>
                <span id="s_name"
                      value="<?php echo $block->getStoreManagerName(); ?>"><?php echo $block->getStoreManagerName(); ?></span>
                <input type="hidden" name="store_mgr_name" value="<?php echo $block->getStoreManagerName(); ?>">
            </p>
        <?php } ?>
        <p>
		<span>
			<strong><?php echo __('Dirección :'); ?></strong>
		</span>
            <span id="address_name"
                  value="<?php echo $block->getStoreAddress(); ?>"><?php echo $block->getStoreAddress(); ?></span>
            <input type="hidden" name="store_address" value="<?php echo $block->getStoreAddress(); ?>">
        </p>
        <p>
            <span id="city_name"
                  value="<?php echo $block->getStoreCity(); ?>"><?php echo $block->getStoreCity(); ?></span>
            <input type="hidden" name="store_city" value="<?php echo $block->getStoreCity(); ?>">
            <?php if (isset($storestate)) { ?>
                <span id="state_name" value="<?php echo $storestate; ?>">,<?php echo $storestate; ?></span>
                <input type="hidden" name="store_state" value="<?php echo $storestate; ?>">
            <?php } ?>
            <span id="s_zipcd" value="<?php echo $storeZipcode; ?>">-<?php echo $storeZipcode; ?></span>
            <input type="hidden" name="store_zipcode" value="<?php echo $storeZipcode; ?>">
        </p>
        <p>
            <span id="s_country" value="<?php echo $storeCountry; ?>"><?php echo $storeCountry; ?></span>
            <input type="hidden" name="store_country" value="<?php echo $storeCountry; ?>">
        </p>
        <p>
		<span>
			<strong><?php echo __('Contacto :'); ?></strong>
		</span>
            <span id="address_name"
                  value="<?php echo $block->getContactNumber(); ?>"><?php echo $block->getContactNumber(); ?></span>
            <input type="hidden" name="store_address" value="<?php echo $block->getContactNumber(); ?>">
        </p>
    </div>
    <div><?= $msg; ?></div>
    <!--<div>
		<span>
			<strong><?php /*echo __('Select Date'); */ ?></strong>
		</span>
		<input type="text" class="input-text" id="calendar_inputField" style="width: 40%" name="store_pckp_date" readonly />
	</div>
	<div id="storeTime">-->

</div>
</div>
<style>
    
.tooltiptextstore{
  width: 100%;
  background-color: #1E2193;
  color: #fff;
  text-align: center;
  border-radius: 6px;
  padding: 5px 5px 5px 5px;
  z-index: 1;
}    

</style>
<script>
    require([
        "jquery",
        "mage/calendar",
    ], function ($) {
        var offdays = new Array();
        <?php foreach($offDays as $val){ ?>
        offdays.push('<?php echo $val; ?>');
        <?php } ?>

        $("#calendar_inputField").datepicker({
            buttonText: "<?php echo __('Select Date') ?>",
            dateFormat: 'dd-mm-yy',
            minDate: 0
        });


    });
</script>
<script type="text/javascript">
    require([
        "jquery",
        "mage/url",
        "mage/calendar",
    ], function ($, url) {
        $("#calendar_inputField").change(function () {
            $(':input[type="submit"]').prop('disabled', true);
            var storepcpdate = $('#calendar_inputField').val();
            var newUrl = url.build('storepick/getday/days/storepkp_date/') + storepcpdate;
            $.ajax({
                method: 'GET',
                dataType: 'html',
                url: newUrl,
            }).success(function (result) {
                if ($('#storeTime').length) {
                    $('#storeTime').empty();
                }
                if (result.indexOf('closed') != -1) {
                    $(':input[type="submit"]').prop('disabled', true);
                } else {
                    $(':input[type="submit"]').prop('disabled', false);
                }
                $('#storeTime').append(result);

            });
        })
    });
</script>
<?php die; ?>

