<?php
/**
 * @var $block \ITM\Sportires\Block\Newsearch
 */


    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
    $noMostrar = array('sportires_product_filterlist','catalog_category_view','checkout_index_index');

    if(!in_array($request->getFullActionName(),$noMostrar)){
?>
<div style="min-height: 125px;"></div>
<?php
}
?>

<div class="new-search">
	<div class="container">
		<div class="search-row">
			<div class="result">

				<?php 
					$text = $block->getSearch();
					$controller = $block->getController();
					echo $text;
					if(strlen($text) < 10 &&  $controller != 'category')
					{
						$blockObj= $block->getLayout()->createBlock('Magento\Catalog\Block\Product\View');
						$_product = $blockObj->getProduct();
						//echo $_product->getName();
					}
				?>
			</div>
			<div class="new-search-link">
				<a  class="action submit primary btn" href="#" id="click-me"><?= __('New Search') ?></a>
			</div>
		</div>
	</div>
</div>
<div id="popup-mpdal" >
	<div class="filter-container" style="display:none">
		<?php echo $this->getLayout()
			->createBlock("ITM\Sportires\Block\Filterblock")
			->setTemplate("ITM_Sportires::filter_block.phtml")
			->toHtml()
		?>
	</div>
</div>

<script>
	require(
		[
			'jquery',
			'Magento_Ui/js/modal/modal'
		],
		function(
			$,
			modal
		) {
			var options = {
				type: 'popup',
				responsive: true,
				innerScroll: true,
				modalClass: 'search',
			};
			
			var popup = modal(options, $('#popup-mpdal'));
			$("#click-me").on('click',function(){
				$("#popup-mpdal").modal("openModal");
				$(".filter-container").show();
			});

		}
	);
</script>