<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Checkout\Block\Cart\Sidebar */
    $idCheckout = 0;
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
    $isCustomer = $request->getFullActionName();
    $isCustomer = substr($isCustomer,0,9);
    if($request->getFullActionName() == 'checkout_index_index'){
        $idCheckout = 1;
    }
?>

<div data-block="minicart" class="minicart-wrapper">
    <a class="action showcart" href="<?php echo $block->getShoppingCartUrl(); ?>"
       data-bind="scope: 'minicart_content'">
        <span class="text"><?php echo __('Cart'); ?></span>
        <span class="counter qty empty"
              data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            <span class="counter-number">
            <!-- ko if: getCartParam('summary_count') --><!-- ko text: getCartParam('summary_count') --><!-- /ko --><!-- /ko -->
            <!-- ko ifnot: getCartParam('summary_count') -->0<!-- /ko -->
            </span>
            <span class="counter-label">
                <!-- ko i18n: 'items' --><!-- /ko -->
            </span>
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart empty"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                "appendTo":"[data-block=minicart]",
                "triggerTarget":".showcart",
                "timeout": "2000",
                "closeOnMouseLeave": false,
                "closeOnEscape": true,
                "triggerClass":"active",
                "parentClass":"active",
                "buttons":[]}}'>
            <div id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>
    <?php endif ?>
    <script>
        window.checkout = <?php echo \Zend_Json::encode($block->getConfig()); ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?php echo $block->getJsLayout();?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?php echo $block->getViewFileUrl('images/loader-1.gif'); ?>"
        }
    }
    </script>
</div>

<script>
    require(
        [
            'jquery'
        ],
        function(
            $,
            modal
        ) {
            
            var isVersonResponsive = $('.nav-toggle').css('display');
            console.log('Version Responsibe '+isVersonResponsive);
             $('.account-nav').remove();
            if(isVersonResponsive == 'block'){
                console.log('Estamos en el Checkout : <?= $idCheckout ?>');
                if('<?= $idCheckout ?>' == '1'){
                    $('.nav-toggle').remove();
                }
            }
            $('.showcart').click(function(){
                console.log('Clic en mini carrito');
                if(isVersonResponsive == 'block'){
                    console.log('Redireccionando '+$(this).attr('href'));
                    window.location.href = $(this).attr('href');
                }
            });

        }
    );
</script>
