<?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
    $noMostrar = array('sportires_product_filterlist','catalog_category_view','catalog_product_view','checkout_index_index');

    if(!in_array($request->getFullActionName(),$noMostrar)){
?>
<div style="min-height: 125px;"></div>
<?php
	}
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

$target_id = $block->getTargetId();
?>
<a id="<?= /* @escapeNotVerified */ $target_id ?>" tabindex="-1"></a>
