<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\CatalogInventory\Block\Stockqty\DefaultStockqty
 */
?>
<?php if ($block->isMsgVisible()): ?>

<?php 
$qty = $block->getStockQtyLeft();
if($block->getStockQtyLeft() > 8){
	$qty = 8;
}
?>

    <div class="availability only" title="<?= /* @escapeNotVerified */ __('Only %1 left', ($qty)) ?>">
        <?= /* @escapeNotVerified */ __('Only %1 left', "<strong>{$qty}</strong>") ?>
    </div>
<?php endif ?>
