<?php
    $header_type = $this->getConfig('porto_settings/header/header_type');
    $header_new_skin = $this->getConfig('porto_settings/header/new_skin');
    $class = $header_type == 17 || $header_type == 19 || $header_type == 16 || $header_type == 20 ? 'header-newskin':'';
    if(isset($header_new_skin) && $header_new_skin && ($header_type == 2 || $header_type == 5 || $header_type == 6 || $header_type == 7 || $header_type == 8 || $header_type == 13))
        $class = 'header-newskin';
    if(isset($header_new_skin) && $header_new_skin && $header_type == 10)
        $class = 'header-new-skin';

    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $request = $objectManager->get('Magento\Framework\App\Action\Context')->getRequest();
    $storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $baseUrl = $storeManager->getStore()->getBaseUrl();

    if($request->getFullActionName() != 'checkout_index_index'){

?>
<script>
    
    var mageplazaSearchProducts = '';
</script>
<div class="head_wrap_custom">
<header class="page-header type<?php echo $header_type; ?> <?php echo $class;?>" >
<?php echo $this->getChildHtml("header_customer_form_login"); ?>
<?php if($header_type == 3 || $header_type == 4 || $header_type == 9): ?>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
        <div class="panel header">
            <div class="top-panel">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
                <?php echo $this->getChildHtml("header.links"); ?>
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
            </div>
            <div class="bottom-panel">
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
            </div>
        </div>
    </div>
<?php elseif($header_type == 12): ?>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
        <div class="panel header">
            <div class="top-panel">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
                <div class="top-links-area">
                    <a class="top-links-icon" href="javascript:void(0)">links</a>
                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>
                <?php echo $this->getChildHtml("custom_block"); ?>
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
            </div>
            <div class="bottom-panel">
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
            </div>
        </div>
    </div>
<?php elseif($header_type == 13): ?>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
        <div class="panel header">
            <div class="top-panel">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <div class="menu-area">
                    <a href="javascript:void(0)" class="shop-menu">Shop</a>
                    <?php echo $this->getChildHtml("navigation.sections"); ?>
                </div>
                <div class="top-links-area">
                    <a class="top-links-icon" href="javascript:void(0)">links</a>
                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>
                <?php if(isset($header_new_skin) && $header_new_skin):?>
                <?php echo $this->getChildHtml("custom_block"); ?>
                <?php endif;?>
            </div>
            <div class="bottom-panel">
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
                <?php echo $this->getChildHtml("minicart"); ?>
            </div>
        </div>
    </div>
<?php elseif($header_type == 5): ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php if(isset($header_new_skin) && $header_new_skin):?>
            <div class="top-links-area">
                <div class="top-links-icon"><a href="javascript:void(0)"><?php echo __('links');?></a></div>
                <?php echo $this->getChildHtml("header.links"); ?>
            </div>
            <?php echo $this->getChildHtml("custom_block"); ?>
            <?php endif;?>
            <?php if(!isset($header_new_skin) || !$header_new_skin):?>
            <?php echo $this->getChildHtml("header.links"); ?>
            <?php endif;?>
        </div>
    </div>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
        <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
        <div class="search-area">
            <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
            <?php echo $this->getChildHtml("top.search"); ?>
        </div>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
    </div>
<?php elseif($header_type == 6): ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
        <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
        <div class="search-area">
            <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
            <?php echo $this->getChildHtml("top.search"); ?>
        </div>
        <?php echo $this->getChildHtml("custom_block"); ?>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
    </div>
<?php elseif($header_type == 7 ): ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php if(!isset($header_new_skin) || !$header_new_skin): ?>
            <?php echo $this->getChildHtml("minicart"); ?>
            <?php endif; ?>
            <div class="search-area">
                <a href="javascript:void(0)" class="search-toggle-icon"><em class="porto-icon-search"></em><?php echo __('Search'); ?></a>
                <?php echo $this->getChildHtml("top.search"); ?>
            </div>
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php if(isset($header_new_skin) && $header_new_skin): ?>
            <?php echo $this->getChildHtml("minicart"); ?>
            <?php endif; ?>
            <span class="split"></span>
            <div class="toplinks-area">
                <a href="javascript:void(0)" class="top-links-icon"><?php echo __('Links'); ?></a>
                <?php echo $this->getChildHtml("header.links"); ?>
            </div>
            <span class="split"></span>
            <?php echo $this->getChildHtml("custom_block"); ?>
        </div>
    </div>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
    </div>
<?php elseif($header_type == 8): ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("minicart"); ?>
    <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
    <?php echo $this->getChildHtml("top.search"); ?>
    <?php echo $this->getChildHtml("custom_block"); ?>
    </div>
    <div class="menu-container">
        <?php
            $toggle_text = $this->getConfig('porto_settings/header/toggle_text');
            $custom_block_id_8 =$this->getConfig('porto_settings/header/static_block_8');
        ?>
        <div class="container">
            <div class="menu-wrapper">
                <div class="drop-menu">
                    <a href="javascript:void(0)">
                        <?php echo $toggle_text; ?>
                    </a>
                    <?php echo $this->getChildHtml("navigation.sections"); ?>
                </div>
                <div class="custom-menu-block">
                <?php
                    $block = $this->getLayout()->createBlock('Magento\Cms\Block\Block');
                    if($block) {
                        $block->setBlockId($custom_block_id_8);
                    }
                    if($block){
                        echo $block->toHtml();
                    }
                ?>
                </div>
            </div>
        </div>
    </div>
<?php elseif($header_type == 10): ?>
    <div class="switcher-area">
        <?php echo $this->getChildHtml("skip_to_content"); ?>
        <?php echo $this->getChildHtml("currency"); ?>
        <?php echo $this->getChildHtml("store_language"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
    </div>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
    <?php if(isset($header_new_skin) && $header_new_skin):?>
    <?php echo $this->getChildHtml("top.search"); ?>
    <?php endif;?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
    <?php if(!isset($header_new_skin) || !$header_new_skin):?>
    <?php echo $this->getChildHtml("top.search"); ?>
    <?php endif;?>
    </div>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div>
    <div class="custom-block-area">
        <?php echo $this->getChildHtml("custom_block"); ?>
    </div>
<?php elseif($header_type == 14 ): ?>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
        <div class="panel header">
            <div class="top-panel">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <?php echo $this->getChildHtml("header.links"); ?>
            </div>
            <div class="bottom-panel">
                <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i><span><?php echo __('Search'); ?></span></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
            </div>
        </div>
        <?php echo $this->getChildHtml("minicart"); ?>
    </div>
<?php elseif($header_type == 15 ): ?>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
        <div class="header-right-area">
            <div class="switcher-area">
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i><span><?php echo __('Search'); ?></span></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
                <div class="cart-area">
                    <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
                    <?php echo $this->getChildHtml("currency"); ?>
                    <?php echo $this->getChildHtml("store_language"); ?>
                    <?php echo $this->getChildHtml("minicart"); ?>
                </div>
            </div>
            <div class="header-link-area">
                <div class="top-links-area panel header">
                    <?php echo $this->getChildHtml("skip_to_content"); ?>
                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>
                <div class="main-link">
                    <?php echo $this->getChildHtml("navigation.sections"); ?>
                </div>
            </div>
        </div>
    </div>
<?php elseif($header_type == 2 && isset($header_new_skin) && $header_new_skin): ?>

    <div class="main-panel-top">
        <div class="container">
            <div class="main-panel-inner">
                <div class="panel wrapper">
                    <div class="panel header">	
				<?php
					echo $this->getLayout()
					->createBlock('Magento\Cms\Block\Block')
					->setBlockId('new_header_bar_top')
					->toHtml();
					?>
                        <?php echo $this->getChildHtml("skip_to_content"); ?>
                        <?php echo $this->getChildHtml("currency"); ?>
                        <?php echo $this->getChildHtml("store_language"); ?>
						<div class="onlymobileheader">
                        <?php echo $this->getChildHtml("header.links"); ?>
						</div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header content">
        <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
		<div class="wrap_header_new col-xs-12 col-sm-12 col-md-12">
		<div class="menu_new_header col-xs-9 col-sm-7 col-md-9">
			<?php echo $this->getChildHtml("logo"); ?>
		<?php echo $this->getChildHtml("navigation.sections"); ?>
		</div>
		<div class="search_header  col-xs-3 col-sm-5 col-md-3">
		 <?php echo $this->getChildHtml("top.search"); ?>
         <?php //echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Amasty_SocialLogin::social.phtml")->toHtml(); ?>
 		 <div class="mobile_only_minicart">
			<?php echo $this->getChildHtml("minicart"); ?> 
		</div>
		</div>
		 </div>
    </div>
<?php elseif($header_type == 18 ): ?>
    <div class="main-panel-top">
        <div class="container">
            <div class="main-panel-inner">
                <div class="panel wrapper">
                    <div class="panel header">
                        <?php echo $this->getChildHtml("skip_to_content"); ?>
                        <?php echo $this->getChildHtml("header.links"); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header content">
        <div class="select-area">
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
        </div>
        <?php echo $this->getChildHtml("logo"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
        <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
        <?php echo $this->getChildHtml("top.search"); ?>
    </div>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
<?php elseif($header_type == 20 ): ?>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
        <div class="panel header">
            <div class="top-panel">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
            </div>
            <div class="bottom-panel">
                <div class="top-links-area">
                    <div class="top-links-icon"><a href="javascript:void(0)"><?php echo __('links');?></a></div>
                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>
                <?php echo $this->getChildHtml("custom_block"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
            </div>
        </div>
    </div>
<?php elseif($header_type == 17 ): ?>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <div class="panel header">
            <div class="top-panel">
                <?php echo $this->getChildHtml("skip_to_content"); ?>
                <?php echo $this->getChildHtml("custom_block"); ?>
                <div class="top-links-area">
                    <div class="top-links-icon"><a href="javascript:void(0)"><?php echo __('links');?></a></div>
                    <?php echo $this->getChildHtml("header.links"); ?>
                </div>
                <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
                <div class="search-area">
                    <a href="javascript:void(0)" class="search-toggle-icon"><i class="porto-icon-search"></i></a>
                    <?php echo $this->getChildHtml("top.search"); ?>
                </div>
            </div>
            <div class="bottom-panel">
                <?php echo $this->getChildHtml("currency"); ?>
                <?php echo $this->getChildHtml("store_language"); ?>
                <?php echo $this->getChildHtml("minicart"); ?>
            </div>
        </div>
        <?php echo $this->getChildHtml("navigation.sections"); ?>
    </div>
<?php elseif($header_type == 19 ): ?>
    <div class="header content">
        <?php echo $this->getChildHtml("logo"); ?>
        <?php echo $this->getChildHtml("minicart"); ?>
        <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
        <?php echo $this->getChildHtml("top.search"); ?>
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <div class="top-links-area">
                <div class="top-links-icon"><a href="javascript:void(0)"><?php echo __('links');?></a></div>
                <?php echo $this->getChildHtml("header.links"); ?>
            </div>
        </div>
    </div>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
<?php else: ?>
    <div class="panel wrapper">
        <div class="panel header">
            <?php echo $this->getChildHtml("skip_to_content"); ?>
            <?php echo $this->getChildHtml("currency"); ?>
            <?php echo $this->getChildHtml("store_language"); ?>
            <?php echo $this->getChildHtml("header.links"); ?>
        </div>
    </div>
    <div class="header content">
    <?php echo $this->getChildHtml("logo"); ?>
    <?php echo $this->getChildHtml("minicart"); ?>
    <span data-action="toggle-nav" class="action nav-toggle"><span><?php /* @escapeNotVerified */ echo __('Toggle Nav') ?></span></span>
    <?php echo $this->getChildHtml("top.search"); ?>
    <?php echo $this->getChildHtml("custom_block"); ?>
    </div>
    <?php echo $this->getChildHtml("navigation.sections"); ?>
<?php endif; ?>
</header>
</div>


<?php }else{ ?>
<script>
    require([
    'jquery'
], function ($) {

    $('.minicart-wrapper').remove();

    $('.row').css({ 'width' : '102%', 'opacity' : '' });
});

</script>

    <div class="main-panel-top">
        <div class="container">
            <div class="main-panel-inner">
                <div class="panel wrapper">
                    <div class="panel header">  
                <?php
                    echo $this->getLayout()
                    ->createBlock('Magento\Cms\Block\Block')
                    ->setBlockId('new_header_bar_top_checkout')
                    ->toHtml();
                    ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="header content header-menus">
        <div class="wrap_header_new col-xs-12 col-sm-12 col-md-12">
        <div class="menu_new_header col-xs-9 col-sm-7 col-md-9">
            <?php echo $this->getChildHtml("logo"); ?>

                <div class="col-sm-6 col-md-3 col-lg-3 d-none d-sm-block phoneicon"><img src="<?= $baseUrl; ?>pub/media/wysiwyg/headertop/whatsapp-icon.png" alt=""><div class="custom-block"> <span style="margin-top:4px;display:block;font-weight:600;">
                <a href="tel:5556366099"><span class="llamanos"> Llámanos</span><br>
                <span style="color:rgb(30,33,147)!important;font-size:14px;display:block;line-height:27px;"></span></a><a class="phno" href="tel:5556366099"> 55 5636 6099</a> </span>
                </div></div>

                <div class="col-sm-6 col-md-3 col-lg-3 d-none d-sm-block whatsapp-greenicon"><img src="<?= $baseUrl; ?>pub/media/wysiwyg/headertop/whatsapp-green.png" alt="">
                <a href="https://api.whatsapp.com/send?phone=5215536558444" target="_blank"><span class="wtsap">Whatsapp</span><br> <span class="wtsno">55 3655 8444</span></a></div>

        </div>
         </div>
    </div>
<?php } ?>


<script>
require([
    'jquery'
], function ($) {
    $(function(){
        var intFrameWidth = window.innerWidth;
        if(intFrameWidth <768){
         var shrinkHeader = 2;
          $(window).scroll(function() {
            var scroll = getCurrentScroll();
              if ( scroll >= shrinkHeader ) {
                   $('header').addClass('shrink');
                }
                else {
                    $('header').removeClass('shrink');
                }
          });
        function getCurrentScroll() {
            return window.pageYOffset || document.documentElement.scrollTop;
            }
        }
    });

    $(function(){
        var intFrameWidth = window.innerWidth;
        if(intFrameWidth > 767){
         var shrinkHeader = 2;
          $(window).scroll(function() {
            var scroll = getCurrentScroll();
              if ( scroll >= shrinkHeader ) {
                   $('header').addClass('sticky-small');
                }
                else {
                    $('header').removeClass('sticky-small');
                }
          });
        function getCurrentScroll() {
            return window.pageYOffset || document.documentElement.scrollTop;
            }
        }
    }); 
    $(function(){
        
        
        function fn60sec() {
            var options = {
                timeZone: 'America/Mexico_City',
                year: 'numeric', month: 'numeric', day: 'numeric',
                hour: 'numeric', minute: 'numeric', second: 'numeric',
            },
                formatter = new Intl.DateTimeFormat([], options)
                // var  time = formatter.format(new Date())
                // var  time = (new Date()).toLocaleString([], options);
                var date = new Date();
                var  time = date.toLocaleString('en-US', {hour: '2-digit',   hour12: false, timeZone: 'America/Mexico_City' });
                var day = date.getDay('en-US', {timeZone: 'America/Mexico_City' });
                //console.log(day);
            // var today = new Date();
            // runs every 60 sec and runs on init.
            // var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
            //console.log(time);
            // console.log(time.getHours());
            
            // var current_hrs = today.getHours();
            // var current_min = today.getMinutes();
            // var current_sec = today.getSeconds();
             if(day == 6 || day == 0){
                if(parseInt(time) > 8 && parseInt(time) < 14 ){
                  // if(current_min > 0 ){
                       $('.msgopen p').text('9 a 14 hrs.');
                       $('.msg_tab_only .msgopen p').text('Atención Telefónica de 9 a 18 hrs Lunes a Sábado');
                       $('.msgopen').css('display','block');
                       $('.msgclose').css('display','none');
                  // }
                }else{
                    $('.msgopen').css('display','none');
                    $('.msgclose').css('display','block');
                }
             }else{
             if(parseInt(time) > 8 && parseInt(time) < 18 && day != 7){
                  // if(current_min > 0 ){
                       $('.msgopen').css('display','block');
                       $('.msgclose').css('display','none');
                  // }
             }else{
                $('.msgopen').css('display','none');
                $('.msgclose').css('display','block');
             }
            }
        }
        fn60sec();
        setInterval(fn60sec, 60*1000);
        
    }); 
    $(function(){
    
        $("body").on("touchstart","ul.header.links li.authorization-link",function(){
            var cls = $('html').attr('class');
            setTimeout(function(){
                $('html').removeClass(cls);
             }, 100);
        });
        $("body").on("touchstart","ul.header.links li:last-child",function(){
            var cls = $('html').attr('class');
            setTimeout(function(){
                $('html').removeClass(cls);
             }, 100);
        });

     }); 
});
</script>