<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
                 alt="<?= /* @escapeNotVerified */ __('Loading...') ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @escapeNotVerified */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>");
            return url.setBaseUrl('<?= /* @escapeNotVerified */ $block->getBaseUrl() ?>');
        })
    </script>
</div>
<script>
    require([
        "jquery",
    ], function ($) {
        
        setInterval(function(){ 
           var prende = $('#pagoOtraSucursal').val();
           $('.col-method .radio').each(function(){
            var selected = $(this).is(':checked');
            var method = $(this).val();
            if(selected == true){
                //$('#classyllama_llamacoin').parent().show();
                //$('#stripe_payments').parent().show();
                if(method == 'flatrate_flatrate' || method == 'instalacion_instalacion'){
                    $('#cashondelivery').parent().hide();
                    $('#classyllama_llamacoin').parent().show();
                    $('#stripe_payments').parent().show();
                }else{
                    if(prende == 'otraSucursal'){
                        $('#cashondelivery').parent().hide();
                        $('#classyllama_llamacoin').parent().show();
                        $('#stripe_payments').parent().show();
                    }else{
                        $('#cashondelivery').parent().show();
                        $('#classyllama_llamacoin').parent().hide();
                        $('#stripe_payments').parent().hide();
                    }
                    
                }
            }
            //console.log('PMetodo de envio seleccionado '+selected+' method '+method);
           });
            
        }, 1000);
        

    });
</script> 